# Generated by Django 5.2.11 on 2026-02-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='crn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='grading_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='unweighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
