# Generated by Django 5.2.12 on 2026-03-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_userprofile_coursemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
