# Generated by Django 5.2.11 on 2026-03-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_userprofile_coursemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
