# Generated by Django 5.2.12 on 2026-03-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_remove_global_grading_assistant_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty / Professor'), ('GRADING_ASSISTANT', 'Grading Assistant'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
