# Generated by Django 5.2.11 on 2026-03-15 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_add_course_is_archived'),
        ('professor', '0007_message'),
    ]

    operations = [
    ]
