# Generated by Django 5.2.11 on 2026-03-16 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0008_merge_conflicting_roles_and_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role_in_course', models.CharField(default='STUDENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_enrollments', to='professor.course')),
            ],
            options={
                'unique_together': {('course', 'email')},
            },
        ),
    ]
