services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./app/data:/app/data
    ports:
      - "80:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
