# Generated by Django 5.2.11 on 2026-03-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_assignment_allowed_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_likelihood_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='plagiarism_confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='plagiarism_match_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='plagiarism_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
