# Generated by Django 5.2.12 on 2026-03-15 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_rubric_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='starter_code',
            field=models.FileField(blank=True, help_text='Optional starter code file for students', null=True, upload_to='starter_code/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='test_cases_file',
            field=models.FileField(blank=True, help_text='JSON file containing test cases with public/private split', null=True, upload_to='test_cases/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='max_score',
            field=models.IntegerField(default=0, help_text='Maximum points possible'),
        ),
        migrations.AddField(
            model_name='submission',
            name='rule_violations',
            field=models.TextField(blank=True, help_text='JSON list of rule violations found'),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('grading', 'Grading'), ('graded', 'Graded'), ('failed', 'Failed')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_score',
            field=models.IntegerField(default=0, help_text='Total points earned from test cases'),
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_functions', models.TextField(blank=True, help_text="Comma-separated list of required function names (e.g., 'main, validate, check_palindrome')")),
                ('forbidden_keywords', models.TextField(blank=True, help_text="Comma-separated list of forbidden keywords (e.g., 'global, break, continue')")),
                ('requires_docstring', models.BooleanField(default=False, help_text='If True, all functions must have docstrings')),
                ('max_function_length', models.IntegerField(blank=True, help_text='Maximum lines per function', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruleset', to='grading.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Test Case', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this test case checks')),
                ('input_data', models.TextField(blank=True, help_text='Input to pass to the program (stdin)')),
                ('expected_output', models.TextField(help_text='Expected output from the program (stdout)')),
                ('points_awarded', models.IntegerField(default=1, help_text='Points awarded for passing this test case')),
                ('is_hidden', models.BooleanField(default=False, help_text='If True, students cannot see input/output during practice')),
                ('order', models.IntegerField(default=0, help_text='Order in which to display test cases')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases_db', to='grading.assignment')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False, help_text='True if actual output matches expected output')),
                ('actual_output', models.TextField(blank=True, help_text='Actual output from code execution')),
                ('error_message', models.TextField(blank=True, help_text='Any error/stderr from execution')),
                ('execution_time', models.FloatField(default=0.0, help_text='Execution time in seconds')),
                ('points_earned', models.IntegerField(default=0, help_text='Points awarded for this test (0 or test_case.points_awarded)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='grading.submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='grading.testcase')),
            ],
            options={
                'ordering': ['test_case__order', 'created_at'],
                'unique_together': {('submission', 'test_case')},
            },
        ),
    ]
