# Generated by Django 5.2.12 on 2026-03-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_assignment_starter_code_assignment_test_cases_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If True, test is private (grading only). If False, test is public (students can run)'),
        ),
    ]
