# Generated by Django 5.2.12 on 2026-03-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_testcase_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_weighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
