# Generated by Django 6.0.1 on 2026-03-27 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0008_assignment_is_weighted_assignment_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='plagiarism_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plagiarized_by', to='grading.submission'),
        ),
    ]
