# Generated by Django 6.0.1 on 2026-03-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0011_alter_submission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_group_size',
            field=models.PositiveIntegerField(default=5, help_text='Maximum students allowed in a group if this is a group assignment.'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='allowed_language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java')], default='python', max_length=10),
        ),
    ]
