# Generated by Django 6.0.1 on 2026-03-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0014_coursegroupset_coursegroup_coursegroupmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_segments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
