# Generated by Django 6.0.1 on 2026-04-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0017_assignment_grades_released_to_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="grades_released_to_students",
            field=models.BooleanField(
                default=True,
                help_text="When off, students see submission status but numeric scores stay hidden until you release grades.",
            ),
        ),
    ]
