# Generated by Django 5.2.11 on 2026-02-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
