# Generated by Django 5.2.11 on 2026-02-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_assignment_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allowed_language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java')], default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='expected_outputs',
            field=models.FileField(blank=True, null=True, upload_to='expected_outputs/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='no_due_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='public_test_data',
            field=models.FileField(blank=True, null=True, upload_to='test_data/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20),
        ),
    ]
