# Generated by Django 5.2.11 on 2026-03-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('compile_command', models.CharField(blank=True, help_text='e.g. javac Main.java (Leave blank for interpreted languages)', max_length=255, null=True)),
                ('run_command', models.CharField(help_text='e.g. python main.py or java Main', max_length=255)),
                ('status', models.BooleanField(default=True, verbose_name='Enabled')),
                ('container_image', models.CharField(help_text='e.g. python:3.10-slim', max_length=255)),
                ('memory_limit_mb', models.IntegerField(default=256, help_text='Memory limit in MB')),
                ('time_limit_ms', models.IntegerField(default=5000, help_text='Time limit in milliseconds')),
            ],
            options={
                'verbose_name': 'Programming Language',
                'verbose_name_plural': 'Programming Languages',
            },
        ),
    ]
