# Generated by Django 5.2.11 on 2026-03-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_programminglanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_limit', models.CharField(choices=[('1 core', '1 core'), ('2 cores', '2 cores'), ('4 cores', '4 cores')], default='1 core', max_length=50)),
                ('memory_limit', models.CharField(choices=[('512 MB', '512 MB'), ('1 GB', '1 GB'), ('2 GB', '2 GB'), ('4 GB', '4 GB')], default='1 GB', max_length=50)),
                ('execution_timeout', models.IntegerField(default=10, help_text='Timeout in seconds')),
                ('container_isolation', models.BooleanField(default=True)),
                ('network_access', models.BooleanField(default=False)),
                ('file_system_access', models.CharField(choices=[('Read only', 'Read only'), ('Restricted Write', 'Restricted Write'), ('Full Access (Admin only)', 'Full Access (Admin only)')], default='Restricted Write', max_length=50)),
                ('enable_auto_scaling', models.BooleanField(default=False)),
                ('max_concurrent_jobs', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Execution Environment',
                'verbose_name_plural': 'Execution Environments',
            },
        ),
    ]
