# Generated by Django 5.2.11 on 2026-03-01 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_executionenvironment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='CSCI-xxxx', help_text='Course code', max_length=50)),
                ('title', models.CharField(default='Untitled Course', help_text='Name of the course', max_length=200)),
                ('term', models.CharField(default='Spring 2026', max_length=50)),
                ('professor_id', models.UUIDField(blank=True, help_text='Matches User UUID', null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Locks the course from further edits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='DatabaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_period', models.CharField(choices=[('30 Days', '30 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days'), ('1 Year', '1 Year')], default='30 Days', max_length=50)),
                ('auto_cleanup_logs', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Database Settings',
                'verbose_name_plural': 'Database Settings',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'UPLOADED'), ('GRADING', 'GRADING'), ('GRADED', 'GRADED'), ('ERROR', 'ERROR')], default='UPLOADED', max_length=50)),
                ('language', models.CharField(choices=[('python', 'python'), ('java', 'java')], default='python', max_length=50)),
                ('artifact_url', models.CharField(help_text='Download link or storage path', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('python', 'python'), ('java', 'java')], default='python', max_length=50)),
                ('due_at', models.DateTimeField()),
                ('points', models.IntegerField(default=100)),
                ('published', models.BooleanField(default=False)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DROPPED', 'DROPPED')], default='ACTIVE', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.course')),
            ],
        ),
        migrations.CreateModel(
            name='GradeReport',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='items.submission')),
                ('success', models.BooleanField(default=False)),
                ('total_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=100)),
                ('breakdown', models.JSONField(default=list, help_text='[{name, passed, score, max_score, output, error}]')),
                ('feedback', models.JSONField(default=list, help_text='[{category, message, severity}]')),
                ('ai_likelihood', models.FloatField(default=0.0)),
                ('ai_explanation', models.TextField(blank=True)),
                ('plagiarism_matches', models.JSONField(default=list, help_text='[{file, score}]')),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.assignment'),
        ),
        migrations.CreateModel(
            name='TestBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('uploaded_by', models.UUIDField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.assignment')),
            ],
        ),
    ]
