# Generated by Django 5.2.11 on 2026-03-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_period', models.CharField(choices=[('30 Days', '30 Days'), ('60 Days', '60 Days'), ('90 Days', '90 Days'), ('1 Year', '1 Year')], default='30 Days', max_length=50)),
                ('auto_cleanup_logs', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Database Settings',
                'verbose_name_plural': 'Database Settings',
            },
        ),
    ]
